### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Gargule** [InfinityRaider/companions#3]
Hey. I know, 1.7.10 dead and everything, but maybe you can fix mod, or at least check why it's crushes?
My guess, it's something between Botania, Baubles, TGear and your mod.
Logs and crush-reports will be in files below, cuz pastebin says that my logs is offensive.
[latest.log](https://github.com/InfinityRaider/companions/files/9136870/latest.log)
[crash-2022-07-19_04.39.14-client.txt](https://github.com/InfinityRaider/companions/files/9136873/crash-2022-07-19_04.39.14-client.txt)

**Comment by Gargule** [comment]
Logs may be kinda useless because of another mod that crashes too, but i had same crush years ago, so problem still present anyways.

**Comment by InfinityRaider** [comment]
This is not caused by companions, this is between botania and traveller's gear.
I'd recommend trying a few different botania versions
